version: '3.4'

x-common-variables: &common-variables
  MYSQL_USER: prisma
  MYSQL_PASSWORD: prisma
  MYSQL_DATABASE: prisma
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:8.0
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prisma
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    # volumes:
    #   - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_DATABASE: prisma
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./server:/app
    links:
      - mysql
    command: sh -c "npm i && npx prisma migrate dev --name init && npm run dev"
  client:
    build:
      context: ./client
      target: builder-client
    ports:
      - 3000:3000
    volumes:
      - ./client/public:/home/node/app/public
      - ./client/src:/home/node/app/src
      - ./client/package.json:/home/node/app/package.json
    links:
      - server
    tty: true
    environment:
      NODE_ENV: 'development'
#  client:
#    build: ./client
#    environment:
#      <<: *common-variables
#      NODE_PATH: src
#    expose:
#      - 3000
#    ports:
#      - 3000:3000
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./client/src:/app/src
#    links:
#      - server
#    command: npm start

# volumes:
#   mysql-data: