version: '3.4'

x-common-variables: &common-variables
  MYSQL_USER: prisma
  MYSQL_PASSWORD: prisma
  MYSQL_DATABASE: prisma
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:8.0
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prisma
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    # volumes:
    #   - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10
    networks:   # Specify the network here
      - REUSABLES

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    restart: always
    networks:
      - REUSABLES

  server:
    build: ./server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_DATABASE: prisma
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./server:/app
    # command: sh -c "npm i && npx prisma migrate dev --name init && npx prisma db seed && npm run dev"
    command: sh -c "npm i && npx prisma migrate dev --name init &&  npm run dev"
    networks:
      - REUSABLES

  client:
    build:
      context: ./client
      target: builder-client
    ports:
      - 3000:3000
    volumes:
      - ./client/public:/home/node/app/public
      - ./client/src:/home/node/app/src
      - ./client/package.json:/home/node/app/package.json
    networks:
      - REUSABLES

networks:
  REUSABLES:   # Define the REUSABLES network
    driver: bridge
